"""Fix UserRole enum values to uppercase

Revision ID: 081a7cdf516b
Revises: d1878bc69d9e
Create Date: 2025-07-04 13:00:52.460112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '081a7cdf516b'
down_revision: Union[str, Sequence[str], None] = 'd1878bc69d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
