"""Add OrderStatus field to orders

Revision ID: 800ebcb2025b
Revises: e141dd5d8e06
Create Date: 2025-07-08 19:18:23.662742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '800ebcb2025b'
down_revision: Union[str, Sequence[str], None] = 'e141dd5d8e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('customer_name', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_address', sa.String(), nullable=True))
    op.create_index(op.f('ix_orders_customer_name'), 'orders', ['customer_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_customer_name'), table_name='orders')
    op.drop_column('orders', 'shipping_address')
    op.drop_column('orders', 'customer_name')
    # ### end Alembic commands ###
