"""Ensure total_price exists in orders

Revision ID: 8992b7537f22
Revises: 9a2945c85a72
Create Date: 2025-07-10 10:07:31.045197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8992b7537f22'
down_revision: Union[str, Sequence[str], None] = '9a2945c85a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Step 1: Add the new column as nullable
    op.add_column('orders', sa.Column('total_price', sa.Float(), nullable=True))

    # Step 2: Populate a default value for existing rows
    op.execute('UPDATE orders SET total_price = 0.0')

    # Step 3: Alter column to be non-nullable
    op.alter_column('orders', 'total_price', nullable=False)

    # Step 4: Add product_name to order_items (this can stay as-is)
    op.add_column('order_items', sa.Column('product_name', sa.String(), nullable=True))

    # Step 5: Drop old total_amount column
    op.drop_column('orders', 'total_amount')



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('orders', 'total_price')
    op.drop_column('order_items', 'product_name')
    # ### end Alembic commands ###
