"""Add OrderStatus field to orders

Revision ID: da23413948c3
Revises: 736977451bc9
Create Date: 2025-07-08 16:01:39.699394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da23413948c3'
down_revision: Union[str, Sequence[str], None] = '736977451bc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('tracking_number', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('shipping_carrier', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipping_carrier')
    op.drop_column('orders', 'tracking_number')
    # ### end Alembic commands ###
