"""Add invoice column to orders

Revision ID: e141dd5d8e06
Revises: da23413948c3
Create Date: 2025-07-08 16:11:55.423632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e141dd5d8e06'
down_revision: Union[str, Sequence[str], None] = 'da23413948c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('invoice', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'invoice')
    # ### end Alembic commands ###
